POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "andy",
    "name": "andres",
    "password": "1234"
}
###
GET http://localhost:3001/api/users
###
GET http://localhost:3001/api/users/663d0c466311aad75b056551
